spring.datasource.url=jdbc:h2:file:./data/academia
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 1. Fuerza la inicialización de scripts de usuario sobre bases de datos basadas en archivos
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# 2. MUY IMPORTANTE: Cambia el orden para que tus scripts se ejecuten ANTES de que Spring Batch inicie
spring.sql.init.order=-2147483648

# 3. Evita que Hibernate intente validar o duplicar la creación de tablas
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.batch.jdbc.initialize-schema=never
spring.batch.job.enabled=true


# Direccion para entrar directo al puerto que abre mongo sin necesidad de pasar por el contenedor docker
spring.data.mongodb.uri=mongodb://localhost:27017/academia
spring.data.mongodb.auto-index-creation=true
#spring.data.mongodb.uri=mongodb://root:root123@localhost:27018/academia?authSource=admin