DROP TABLE IF EXISTS estudiantes_procesados;

CREATE TABLE estudiantes_procesados (
                                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        nombre VARCHAR(100) NOT NULL,
                                        grupo VARCHAR(10) NOT NULL,
                                        nota1 DECIMAL(5,2) NOT NULL,
                                        nota2 DECIMAL(5,2) NOT NULL,
                                        nota3 DECIMAL(5,2) NOT NULL,
                                        promedio DECIMAL(5,2) NOT NULL
);